#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import stanza

from deepnlpf.core.iplugin import IPlugin


class Plugin(IPlugin):
    def __init__(self, document, pipeline):
        self._document = document
        self._processors = pipeline["tools"]["stanza"]["processors"]
        self._lang = pipeline["lang"]

    def run(self):
        doc = self.wrapper()
        doc_annotation = self.out_format(doc)
        return doc_annotation

    def wrapper(self):
        # execulte pipeline.
        nlp = stanza.Pipeline(
            lang=self._lang, processors=", ".join(self._processors), use_gpu=False,
        )

        doc = nlp(" ".join(self._document))

        return doc

    def out_format(self, doc):
        """Format the output to the standard accepted by DeepNLPF.

        Arguments:
            doc {[type]} -- Receives the output generated by the tool.

        Returns:
            [type] -- Returns the output in the pattern defined by DeepNLPF.
        """

        doc_formated = list()

        for _id, sentence in enumerate(doc.sentences):
            token_annotation = list()
            text = list()
            for token in sentence.tokens:
                text.append(token.text)
                token_annotation.append(token)
            doc_formated.append(
                {"_id": _id+1, "text": ", ".join(text), "annotation": token_annotation}
            )

        return doc_formated
